### ISSUE TITLE
How to get it work with Aukey EP-T25-Fedora 32 Copr

### ISSUE THREAD

**Issue by riteshjn** [pali/hsphfpd-prototype#10]
I am trying to make this work on my Fedora machine with Aukey EP-T25 bluetooth earbuds. I tried to install this from the copr repository provided here: 

https://copr.fedorainfracloud.org/coprs/alebastr/hsphfpd/

I am aware that the developer might not be able to support a third party package. Please excuse me if I am submitting this issue at the wrong place.

Now, after setting this up as stated in the copr documentation, I can see the following in output for my device in `pactl list`
```
Card #7
	Name: bluez_card.41_42_96_9E_6C_76
	Driver: module-bluez5-device.c
	Owner Module: 29
	Properties:
		device.description = "AUKEY EP-T25"
		device.string = "41:42:96:9E:6C:76"
		device.api = "bluez"
		device.class = "sound"
		device.bus = "bluetooth"
		device.form_factor = "headphone"
		bluez.path = "/org/bluez/hci0/dev_41_42_96_9E_6C_76"
		bluez.class = "0x240418"
		bluez.alias = "AUKEY EP-T25"
		device.icon_name = "audio-headphones-bluetooth"
	Profiles:
		handsfree_head_unit: Headset Head Unit (HFP) (sinks: 1, sources: 1, priority: 4, available: yes)
		a2dp_sink_sbc_lq: High Fidelity Playback (A2DP Sink) with codec SBC (Low Quality) (sinks: 1, sources: 0, priority: 15, available: yes)
		a2dp_sink_sbc_mq: High Fidelity Playback (A2DP Sink) with codec SBC (Middle Quality) (sinks: 1, sources: 0, priority: 18, available: yes)
		a2dp_sink: High Fidelity Playback (A2DP Sink) with codec SBC (Automatic Quality) (sinks: 1, sources: 0, priority: 19, available: yes)
		a2dp_sink_sbc_hq: High Fidelity Playback (A2DP Sink) with codec SBC (High Quality) (sinks: 1, sources: 0, priority: 21, available: yes)
		a2dp_sink_sbc_xq2: High Fidelity Playback (A2DP Sink) with codec SBC (eXtreme Quality profile 2) (sinks: 1, sources: 0, priority: 24, available: yes)
		off: Off (sinks: 0, sources: 0, priority: 0, available: yes)
	Active Profile: off
	Ports:
		headphone-output: Headphone (type: Headphones, priority: 0, latency offset: 0 usec, availability unknown)
			Part of profile(s): handsfree_head_unit, a2dp_sink_sbc_lq, a2dp_sink_sbc_mq, a2dp_sink, a2dp_sink_sbc_hq, a2dp_sink_sbc_xq2
		headphone-input: Bluetooth Input (type: Bluetooth, priority: 0, latency offset: 0 usec, availability unknown)
			Part of profile(s): handsfree_head_unit

```
As noticed, the `handsfree_head_unit` profile is stated as available. Yet, when I try to switch the headset to this profile from Gnome settings manager, the connection is very brief (milliseconds) and then the active profile switches to `off`. Switching the profile from command line using `pacmd set-card-profile bluez_card.41_42_96_9E_6C_76 handsfree_head_unit` does not throw any errors, but even after this the active profile remains `off`.

Any hints on how can I solve this? Is this is a timeout issue somehow? Pardon my ignorance if I am missing something. I am a linux user, not a developer, and I am finding my way around this whole thing.

**Comment by pali** [comment]
This looks like an issue in pulseaudio. Please report it to pulseaudio developers.

**Comment by alebastr** [comment]
This wasn't an issue in pulseaudio. I forgot that DBus access in Fedora is controlled both with dbus policies and SELinux, thus hsphfpd did not have permissions to contact the audio agent and pass the socket.
@riteshjn, please try updated hsphfpd package with version `0-0.4.20201204git19d44e8`, it would install a SELInux policy that allows hsphfpd to talk with user services.
Please, let me know (directly or via copr discussion feature) if that worked.
***
@pali, I'm grateful for all the work that you've done for Linux bluetooth audio and I'm sad and sorry for the things that happened. If you want me to stop distributing pulseaudio binaries with your changes, I'll do so immediately.

**Comment by pali** [comment]
From @riteshjn description it looked like an issue with pulseaudio. I did not know that this is just another issue that SELinux was incorrectly configured. And because there were no hsphfpd logs and only output from pulseaudio I had an assumption that issue in pulseaudio.

> If you want me to stop distributing pulseaudio binaries with your changes, I'll do so immediately.

I have absolutely no reason to do it. Rather see this page (archived) https://web.archive.org/web/20201205043922/https://gitlab.freedesktop.org/pali to have better image. I was not informed by any representative of freedesktop about this fact.
