### ISSUE TITLE
Youtube video stops when using HFP

### ISSUE THREAD

**Issue by domenkozar** [pali/hsphfpd-prototype#14]
When I switch to HFP/headset profile, youtube video would stop playing. When I switch back to my speakers it works again.

I do see in my logs:

```
Dec 08 17:28:51 guava hsphfpd.pl[18083]: Socket exception on audio transport /org/hsphfpd/hci0/dev_84_76_37_ED_D8_29/audio
Dec 08 17:28:51 guava hsphfpd.pl[18083]: Disconnecting audio transport /org/hsphfpd/hci0/dev_84_76_37_ED_D8_29/audio
Dec 08 17:28:51 guava hsphfpd.pl[18083]: Destroying SCO socket
Dec 08 17:30:09 guava hsphfpd.pl[18083]: Connecting audio transport for endpoint /org/hsphfpd/hci0/dev_84_76_37_ED_D8_29/hfp_hf with air_codec CVSD and agent_codec PCM_s16le_8kHz
Dec 08 17:30:09 guava hsphfpd.pl[18083]: Creating SCO socket
```

But it's hard to say it's related.

I'm using latest patches + master as of today.

**Comment by pali** [comment]
> Dec 08 17:28:51 guava hsphfpd.pl[18083]: Socket exception on audio transport /org/hsphfpd/hci0/dev_84_76_37_ED_D8_29/audio

It means that either local audio agent or remote bluetooth device closed audio part of HFP connection. Seems that nothing related to hsphfpd daemon, it is normal that one side close connection. You just need to figure out why...

**Comment by pali** [comment]
There are no more details, nothing more which can be done. If issue is in pulseaudio then report it to pulseaudio maintainers.
