### ISSUE TITLE
WIDEBAND_SPEECH support ?

### ISSUE THREAD

**Issue by joakim-tjernlund** [pali/hsphfpd-prototype#16]
More and more BT USB adapters are getting the WIDEBAND_SPEECH flag in their drivers.
Is it possible to extend hsphfpd to enable mSBC for such adapters ?

**Comment by pali** [comment]
Closing, hsphfpd has since beginning support for mSBC via software encoding/decoding.

Hardware encoding of mSBC is currently blocked by Linux kernel and cannot be enabled from userspace.
