### ISSUE TITLE
Better call quality than PCM_s16le_8kHz?

### ISSUE THREAD

**Issue by viktormv** [pali/hsphfpd-prototype#17]
Is it currently possible to get better call quality than PCM_s16le_8kHz (like 16kHz with mSBC)?

It seems it always uses 8kHz audio when using HFP profile:
```
Connecting audio transport for endpoint /org/hsphfpd/hci0/dev_41_42_6C_B0_36_4B/hfp_hf with air_codec CVSD and agent_codec PCM_s16le_8kHz
Passing audio transport /org/hsphfpd/hci0/dev_41_42_6C_B0_36_4B/audio to application's :1.137 /SCOEndpoint agent /SCOEndpoint/PCM_s16le_8kHz with codec PCM_s16le_8kHz
```

**Comment by pali** [comment]
See:
https://github.com/pali/hsphfpd-prototype/blob/d294d064879591e9570ca3f444fa3eee2f269df8/hsphfpd.txt#L862-L892

_Currently supported codecs combinations_ contains list of combination allowed by mainline Linux kernel.

CVSD codec is 8kHz therefore connecting it with PCM_s16le_16kHz agent codec does not change quality as it would need to be downscaled to 8kHz.

**Comment by pali** [comment]
So to use different agent codec, you just have to register different agent codec from your application.

**Comment by viktormv** [comment]
Thanks for the quick reply.
I'm using Pulseaudio with the hsphfpd patches.
According to the hsphfpd logs, `mSBC` could be a supported combination, however SCOEndpoint is created with `PCM_s16le_8kHz` codec only:

```
systemd[1]: Started hsphfpd.
hsphfpd.pl[2877]: Creating listening SCO socket
hsphfpd.pl[2877]: Supported codecs combination on SCO socket by kernel:
hsphfpd.pl[2877]: Air codec CVSD with agent codec PCM_s16le_8kHz
hsphfpd.pl[2877]: Air codec mSBC with agent codec mSBC
hsphfpd.pl[2877]: Registered profile hfp_hf
hsphfpd.pl[2877]: Registered profile hsp_hs
hsphfpd.pl[2877]: Registered profile hsp_ag
hsphfpd.pl[2877]: added: profile_manager=/org/bluez
hsphfpd.pl[2877]: Supported air codecs for adapter /org/bluez/hci0:
hsphfpd.pl[2877]: ulaw
hsphfpd.pl[2877]: alaw
hsphfpd.pl[2877]: CVSD
hsphfpd.pl[2877]: AuriStream_2bit_8kHz
hsphfpd.pl[2877]: AuriStream_2bit_16kHz
hsphfpd.pl[2877]: AuriStream_4bit_8kHz
hsphfpd.pl[2877]: AuriStream_4bit_16kHz
hsphfpd.pl[2877]: mSBC
hsphfpd.pl[2877]: Supported agent codecs for adapter /org/bluez/hci0:
hsphfpd.pl[2877]: CVSD
hsphfpd.pl[2877]: mSBC
hsphfpd.pl[2877]: Supported codecs combination for adapter /org/bluez/hci0 by kernel:
hsphfpd.pl[2877]: Air codec CVSD with agent codecs: PCM_s16le_8kHz
hsphfpd.pl[2877]: Air codec mSBC with agent codecs: mSBC
hsphfpd.pl[2877]: added: adapter=/org/bluez/hci0 address=54:8C:A0:70:56:08
hsphfpd.pl[2877]: added: device=/org/bluez/hci0/dev_41_42_6C_B0_36_4B adapter=/org/bluez/hci0 endpoint=/org/hsphfpd/hci0/dev_41_42_6C_B0_36_4B/hfp_hf local_address=54:8C:A0:70:56:08 remote_address=41:42:6C:B0>
hsphfpd.pl[2877]: Registering application :1.76 /SCOEndpoint
hsphfpd.pl[2877]: Registering application's :1.76 /SCOEndpoint audio agent /SCOEndpoint/PCM_s16le_8kHz for codec PCM_s16le_8kHz
```

**Comment by pali** [comment]
> Thanks for the quick reply.
> I'm using Pulseaudio with the hsphfpd patches.

So report this issue to pulseaudio maintainers/admins. This is not problem with hsphfpd. Closing for now.

**Comment by joakim-tjernlund** [comment]
> Thanks for the quick reply.
> I'm using Pulseaudio with the hsphfpd patches.
> According to the hsphfpd logs, `mSBC` could be a supported combination, however SCOEndpoint is created with `PCM_s16le_8kHz` codec only:
> 

If you want mSBC now you need to use pipewire. Pipewire is in active development and mSBC was recently added so there
may be rough edges. You might need to patch the kernel as well.

**Comment by viktormv** [comment]
Thanks, Joakim!

Just to let you know, I finally managed to set up pipewire with hsphfpd and bluez5 mSBC support. Now the hsphfpd logs look promising, mSBC shows up in the registrations:

```
hsphfpd.pl[323]: Registering application :1.42 /Profile/hsphfpd/manager
hsphfpd.pl[323]: Registering application's :1.42 /Profile/hsphfpd/manager audio agent /Profile/hsphfpd/msbc_agent for codec mSBC
hsphfpd.pl[323]: Registering application's :1.42 /Profile/hsphfpd/manager audio agent /Profile/hsphfpd/pcm_s16le_8khz_agent for codec PCM_s16le_8kHz
```
Unfortunately, when I switch to the hsp/hfp profile, the audio transport is still connected with PCM_s16le_8kHz, not mSBC:
`hsphfpd.pl[323]: Connecting audio transport for endpoint /org/hsphfpd/hci0/dev_41_42_6C_B0_36_4B/hfp_hf with air_codec CVSD and agent_codec PCM_s16le_8kHz`
Maybe that kernel patch is still needed to function properly, I'm using kernel version 5.10.6.

**Comment by joakim-tjernlund** [comment]
The kernel patch is still needed. If you after that still have problems I suggest you ask in the pipewire threads.
You should check that your HS is mSBC capable, mine was not :(
I think you can see that in the msgs from hsphfpd, there should be some BAC=1,2 msg there.
