### ISSUE TITLE
Connected but no sound in or out

### ISSUE THREAD

**Issue by moredanphysics** [pali/hsphfpd-prototype#18]
Hi,

First of all, thanks for all your effort in preparing this and making it available.

I followed your instructions on my ArchLinux system (5.10.10-arch1-1). Having unloaded the relevant pa modules, I ran `sudo ./hsphfpd.pl`. This gave the following output:

>Creating listening SCO socket
Supported codecs combination on SCO socket by kernel:
Air codec CVSD with agent codec PCM_s16le_8kHz
Air codec mSBC with agent codec mSBC
Registered profile hfp_hf
Registered profile hsp_hs
Registered profile hsp_ag
added: profile_manager=/org/bluez
Supported air codecs for adapter /org/bluez/hci0:
ulaw
alaw
CVSD
AuriStream_2bit_8kHz
AuriStream_2bit_16kHz
AuriStream_4bit_8kHz
AuriStream_4bit_16kHz
mSBC
Supported agent codecs for adapter /org/bluez/hci0:
ulaw
alaw
AuriStream_2bit_8kHz
AuriStream_2bit_16kHz
AuriStream_4bit_8kHz
AuriStream_4bit_16kHz
mSBC
PCM_s16le_8kHz
PCM_u16le_8kHz
PCM_s8_8kHz
PCM_u8_8kHz
Supported codecs combination for adapter /org/bluez/hci0 by kernel:
Air codec CVSD with agent codecs: PCM_s16le_8kHz
Air codec mSBC with agent codecs: mSBC
added: adapter=/org/bluez/hci0 address=00:02:72:CD:AB:D5
added: device=/org/bluez/hci0/dev_2C_41_A1_87_1E_66 adapter=/org/bluez/hci0 endpoint=/org/hsphfpd/hci0/dev_2C_41_A1_87_1E_66/hsp_hs local_address=00:02:72:CD:AB:D5 remote_address=2C:41:A1:87:1E:66 profile=hsp_hs
added: device=/org/bluez/hci0/dev_2C_41_A1_87_1E_66 adapter=/org/bluez/hci0 endpoint=/org/hsphfpd/hci0/dev_2C_41_A1_87_1E_66/hfp_hf local_address=00:02:72:CD:AB:D5 remote_address=2C:41:A1:87:1E:66 profile=hfp_hf

I then reconnected my (bose qc35 ii) headset to the BT, adding the lines:
>New connection: endpoint=/org/hsphfpd/hci0/dev_2C_41_A1_87_1E_66/hsp_hs profile=hsp_hs device=/org/bluez/hci0/dev_2C_41_A1_87_1E_66 fd=6 version=1.2 features=1
Opening connection for endpoint /org/hsphfpd/hci0/dev_2C_41_A1_87_1E_66/hsp_hs
Supported HS profile features:
volume-control
Creating uinput device for endpoint /org/hsphfpd/hci0/dev_2C_41_A1_87_1E_66/hsp_hs: Bose QC35 II (HSP)
Socket ready read: endpoint=/org/hsphfpd/hci0/dev_2C_41_A1_87_1E_66/hsp_hs
Line: AT+VGS=10
Setting tx volume gain to 10
Socket write: endpoint=/org/hsphfpd/hci0/dev_2C_41_A1_87_1E_66/hsp_hs
Line: OK
Socket ready read: endpoint=/org/hsphfpd/hci0/dev_2C_41_A1_87_1E_66/hsp_hs
Line: AT+XAPL=009E-4020-0481,3
Apple features changed event
Supported Apple features:
apple-battery-level
Socket write: endpoint=/org/hsphfpd/hci0/dev_2C_41_A1_87_1E_66/hsp_hs
Line: +XAPL=iPhone,30
Socket ready read: endpoint=/org/hsphfpd/hci0/dev_2C_41_A1_87_1E_66/hsp_hs
Line: AT+XEVENT=Bose SoundLink,158
Unknown command
Socket write: endpoint=/org/hsphfpd/hci0/dev_2C_41_A1_87_1E_66/hsp_hs
Line: ERROR
Socket ready read: endpoint=/org/hsphfpd/hci0/dev_2C_41_A1_87_1E_66/hsp_hs
Line: AT+IPHONEACCEV=2,1,6,2,0
Apple indicators changed event
Apple battery level changed
Apple dock state changed
Socket write: endpoint=/org/hsphfpd/hci0/dev_2C_41_A1_87_1E_66/hsp_hs
Line: OK

Next I started `./audio_client.pl` and finally executed the `ConnectAudio('','')` D-bus method on the `dev_2C_41_A1_87_1E_66/hsp_hs` `org.hsphfpd.Endpoint`. At this point I heard a low level of white noise start on the headset, which seems as expected for an HSP/HSF connection. I get the impression I can hear outside noise in the headset more, which makes me think that the microphone is active, though. 

However, if I start Skype, I don't hear anything on the microphone at the other end of the call. And if I don't start Skype, the connection seems to be dropped: in the `./audio_client.pl` terminal, I saw the following error appear after about 30 seconds of white-noise inactivity:
>New connection: caller=:1.219 path=/org/hsphfpd/hci0/dev_2C_41_A1_87_1E_66/audio fd=5 mtu=64 air_codec=CVSD
Reading data from SCO socket 5 failed: Software caused connection abort
Closing connection: path=/org/hsphfpd/hci0/dev_2C_41_A1_87_1E_66/audio
write() failed: Broken pipe

Any clues as to how I can advance? I'm sure I misunderstand a great deal at this point, so I'm grateful for your patience!

**Comment by pali** [comment]
audio_client.pl is just an example application for audio server developers to see how to access bluetooth microphone and speaker. This example application just playbacks bluetooth microphone and send local microphone to bluetooth speaker.

**Comment by moredanphysics** [comment]
Quick reply, thanks, and thanks for correcting my misunderstanding of audio_client.pl. Is it easy for me to test hsphsfd then? Is it expected that extra development is needed to, e.g., use with Skype? 
Apologies for the ignorant questions here.

**Comment by moredanphysics** [comment]
I guess the answer to my question is here:
> If you are using pulseaudio with hsphfpd patches then pulseaudio already
implements needed Audio agent and therefore you should not need to use
example of Audio agent as described below.

So in that case I'd need the pulseaudio hsphfpd patches, in theory. If I've understood correctly, feel free to close the issue. I'll get hold of a bluetooth-usb soundcard for the time being...!

**Comment by pali** [comment]
It is for integrating into audio servers (alsa / pulseaudio), not into end applications (skype). There were patches for pulseaudio but pulseaudio admins decided to ban them.
