### ISSUE TITLE
service friendly?

### ISSUE THREAD

**Issue by joakim-tjernlund** [pali/hsphfpd-prototype#2]
Could  hsphfpd be more service friendly?
Like daemonazing itself? create pid file? restartable ?

**Comment by pali** [comment]
DBus interface does not specify anything about pid file or daemon mode. It is up to the implemenentation what it choose or how to implement it. Implementation is free to choose any technique, including autospawn by dbus daemon itself.

Implementation including in this repository is prototype to show possibilities and implement dbus service as needed and for such thing is not need to have in it.

I would close this issue for now.

If there are any specific issues with dbus interface, please open a new issue and describe **exactly* what is wrong or how should be dbus interface extended. Ideally with proposed change to interface how it should behave and why is such change usefull.

**Comment by joakim-tjernlund** [comment]
Well, I wanted to try out this under some time and then I cannot muck around with
manual starting of hsphfp and then restarting PA.
I created an openrc init file:
```
#!/sbin/openrc-run
# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

pidfile="/run/hsphfpd.pid"
command="/usr/sbin/hsphfpd.pl"
command_background=1

depend() {
	after bluetooth
}
```
this will do for now. I would like to be able to restart hsphfp without having to manually
restart PA too.

**Comment by pali** [comment]
You do not have to restart hsphfpd. It is independent service of audio applications (e.g. pulseaudio).

**Comment by joakim-tjernlund** [comment]
Oh, indpendent? So I can kill the service hsphfpd and start an interactive one without
restating PA too? I just assumed that would not work per you earlier instructions in readme

**Comment by pali** [comment]
> So I can kill the service hsphfpd and start an interactive one without restating PA too?

Yes. After new instance is ready, audio application (pulseaudio) will connect to it.
