### ISSUE TITLE
Full duplex mode seems to be broken

### ISSUE THREAD

**Issue by smikesmike** [pali/hsphfpd-prototype#20]
Hi,
I am using your daemon to connect an Android S20 via a "Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)" to an Ubuntu 20.04 LTS server.

When I either send or receive audio, it is working fine. But when I send and receive audio parallel (full duplex), then only receiving data works.
To verify if tried an echo client which reads from SCO socket and writes the data direct back. But the written audio does not appear on the remote site.

Have you tried and observed this, too? Or could the problem be related to the bluetooth dongle or android device (e.g. echo/noise cancellation)?

BR
Marc

**Comment by pali** [comment]
Hi! I have not seen this issue. Could you try different bluetooth dongle or different device (e.g. regulator bluetooth headphones)?

**Comment by smikesmike** [comment]
Hi, 
I think the daemon is working in duplex mode, but it seems that there is a kind of `echo or noise cancellation` active which mutes my payload. If I send voice data it appears valid at the remote peer.
Do you have an idea how I could discover or disable this?

BR
Marc

**Comment by pali** [comment]
echo canceling and noise reduction is feature of HFP profile and need to be configured at client/hfp side (so at the headphones). This side (headphones) may send request to gateway side (computer) to turn on or off echo canceling and noise reduction at computer side. Therefore your audio agent must implement echo canceling and noise reduction functions and dynamically enable/disable them based on what headphones requests. hsphfpd exports this information via DBus, see NREC property in documentation file hsphfpd.txt. If your audio agent does not implement this properly then you may expect and observe problems.

**Comment by smikesmike** [comment]
Okay, I will discover the NREC property. And maybe I should change the codec from `PCM_s16le_8kHz` to `mSBC`...

Additionally, I am wondering if not the socket option in line 704 has something to do with it:
```
# SOL_BLUETOOTH => 274, BT_VOICE => 11, struct bt_voice { uint16_t setting; }
setsockopt $socket, 274, 11, pack 'S', 0x0060
```
Do you know which values are allowed for the parameter BT_VOICE?

**Comment by pali** [comment]
Yes, I know. Kernel currently does not allow any other value than 0x0060 and 0x0003.

**Comment by smikesmike** [comment]
Okay, I am currently trying some other dongles ("Broadcom Corp. BCM20702A0 Bluetooth 4.0" instead of "Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)"). But now I get the following error:

```
marc@btsvr1804:~$ sudo /etc/init.d/bluetooth status
● bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2021-04-15 08:39:12 UTC; 1h 57min ago
     Docs: man:bluetoothd(8)
 Main PID: 2478 (bluetoothd)
   Status: "Running"
    Tasks: 1 (limit: 9440)
   CGroup: /system.slice/bluetooth.service
           └─2478 /usr/lib/bluetooth/bluetoothd

Apr 15 08:39:12 btsvr1804 systemd[1]: Starting Bluetooth service...
Apr 15 08:39:12 btsvr1804 bluetoothd[2478]: Bluetooth daemon 5.48
Apr 15 08:39:12 btsvr1804 systemd[1]: Started Bluetooth service.
Apr 15 08:39:12 btsvr1804 bluetoothd[2478]: Starting SDP server
Apr 15 08:39:12 btsvr1804 bluetoothd[2478]: Bluetooth management interface 1.14 initialized
Apr 15 08:39:39 btsvr1804 bluetoothd[2478]: a2dp-source profile connect failed for 6C:DD:BC:54:CC:B8: Protocol not available
```

And I still receive this message if I switch back to my old BT dongle. Is there something I could restart to get the `a2dp-source` up again? I've tried restarting bluetooth and also rebooting the system, but without success...

**Comment by pali** [comment]
hsphfpd implements HSP and HFP profiles. bluetoothd implements A2DP profile. Your last post is not related neither to HSP nor HFP nor hsphfpd. So I could help/comment it.

**Comment by smikesmike** [comment]
So, I don't need  bluetoothd for my own HSP-adapter? 

My problem is, that after switching the dongles the SCO socket doesn't work properly. And I thought, that the SCO is provided by bluetoothd...

**Comment by pali** [comment]
bluetoothd is required for hsphfpd. bluetoothd/bluez does not implement HSP nor HFP but provides simple API for external implementation. And hsphfpd uses this API to implement HSP and HFP profiles. Please look into hsphfpd.txt document where it is described (including diagrams).

**Comment by smikesmike** [comment]
Sorry for bother you with my bluez problems. I have totally forgotten about your great API documentation ;)

I was just wondering why a simple `bluetoothctl connect XY` doesn't work anymore after switching the bt dongle.
Is it possible that some bluez module was (re-)activated by plug/unplug the dongle?
(I found only `pactl unload-module module-bluetooth-discover` as active module)

Here is the output from syslog after a connect attemp:
```
Apr 15 12:10:41 btserver systemd[1141]: Reached target Bluetooth.
Apr 15 12:10:43 btserver kernel: [  179.038161] Bluetooth: hci0: command 0x041b tx timeout
Apr 15 12:10:45 btserver kernel: [  181.054551] Bluetooth: hci0: command 0x0c1a tx timeout
Apr 15 12:11:21 btserver bluetoothd[876]: Unable to get Headset Voice gateway SDP record: Connection timed out
Apr 15 12:11:21 btserver bluetoothd[876]: a2dp-source profile connect failed for 6C:DD:BC:54:CC:B8: Protocol not available
Apr 15 12:11:42 btserver bluetoothd[876]: Unable to get Headset unit SDP record: Connection reset by peer
```

Or is there a safe way to restart the bluetooth stack?

**Comment by pali** [comment]
I'm not sure. Note that hsphfpd is designed to work correctly for hotplugging bluetooth adapters and also when bluetoothd daemon restarts. So it should be safe to reload everything.

```
Apr 15 12:11:21 btserver bluetoothd[876]: Unable to get Headset Voice gateway SDP record: Connection timed out
```
This looks like that your bluetooth device does not respond to SDP packet which should return information required for HSP-AG profile.

```
Apr 15 12:11:42 btserver bluetoothd[876]: Unable to get Headset unit SDP record: Connection reset by peer
```
This means like your bluetooth device closed connection during request for SDP packet describing HSP-HS profile.

Other lines are not related to hsp nor hfp profile.

**Comment by smikesmike** [comment]
Hi again.
I'm now a bit further: If I load the modules "module-bluetooth-discover", "module-bluez5-discover" and "module-bluez5-device", then I am able to connect my phone via `bluetoothctl`. 
But then, of course, the `hsphfpd` doesn't work...

Is there a strict, deterministic order for pairing, connecting and unload modules? I am using a minimal ubuntu server 20.04 LTS.

E.g.
- unplug dongle
- restart system
- remove all paired devices (via buetoothctl)
- unload pulse modules ( "module-bluetooth-discover", "module-bluez5-discover" and "module-bluez5-device"). What about `module-bluetooth-policy`?
- restart `bluetoothd`
- start `hsphfpd`. Is a client (e.g. `audio_client.pl`) required for pairing?
- plug BT dongle
- pair, trust, connect BT device

Or should/must the Pulse modules be loaded during initial pairing/connecting? 

BR Marc

**Comment by pali** [comment]
Closing, this is not pulseaudio support forum. Please contact somebody else.

**Comment by smikesmike** [comment]
Sorry, if my question was misunderstanding:
I don't want to use pulseaudio. I just want to get the `hsphfpd` up and running again after changing my BT dongle. 
Before the dongle change I had a rockstable installation. But after removing the paired device I am struggling - since three days - on the initial device/BT setup.

So here one last question (if allowed):
Is PulseAudio required for the initial device (mobile phone) pairing or could it be done with only running hsphfpd?

**Comment by pali** [comment]
No, hsphfpd does not use nor require pulseaudio.
