### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gebner** [pali/hsphfpd-prototype#8]
We want to package hsphfpd for nixos: https://github.com/NixOS/nixpkgs/pull/103225  (It is not only used by the in-progress pulseaudio MR, pipewire also has upstream support for hsphfpd now.)

Can you clarify what license this project is under?  Is it LGPL21 like pulseaudio itself?

**Comment by pali** [comment]
It is under standard Perl license, same as my other tools and modules written in Perl.

**Comment by pali** [comment]
API is obviously not licensed.

**Comment by gebner** [comment]
Thanks!
