### ISSUE TITLE
Does not work for Freebuds Pro

### ISSUE THREAD

**Issue by svenihoney** [pali/hsphfpd-prototype#9]
I have a nice little pair of Huawei Freebuds Pro lying around here and try to get them to work with your interesting project. But I always get an error if I try to do so.

System: Manjaro
Packages from AUR:
aur/hsphfpd-git r13.601bf8f-1 [installiert: r17.6341793-1] (3, 1.65)
aur/libpulse-hsphfpd 14.0+116+gd2ea10877-1 [installiert: 14.0+117+g16a30be71-1] (3, 1.44)
aur/pulseaudio-bluetooth-hsphfpd 14.0+116+gd2ea10877-1 [installiert: 14.0+117+g16a30be71-1] (3, 1.44)
aur/pulseaudio-hsphfpd 14.0+116+gd2ea10877-1 [installiert: 14.0+117+g16a30be71-1] (3, 1.44)

```
# bluetoothctl info                                                                                                      ✔ 
Device 00:66:19:XX:XX:XX (public)
        Name: HUAWEI FreeBuds Pro
        Alias: HUAWEI FreeBuds Pro
        Class: 0x00240418
        Icon: audio-card
        Paired: yes
        Trusted: yes
        Blocked: no
        Connected: yes
        LegacyPairing: no
        UUID: Serial Port               (00001101-0000-1000-8000-00805f9b34fb)
        UUID: Audio Sink                (0000110b-0000-1000-8000-00805f9b34fb)
        UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
        UUID: Advanced Audio Distribu.. (0000110d-0000-1000-8000-00805f9b34fb)
        UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
        UUID: Handsfree                 (0000111e-0000-1000-8000-00805f9b34fb)
        UUID: Huawei Technologies Co... (0000fd9a-0000-1000-8000-00805f9b34fb)
        ManufacturerData Key: 0x027d
        ManufacturerData Value:
  17 16 ee fd 01 01 01 02 c7 03 00 00 3c 04 00 0f  ............<...
  01 10 01 11 ef 13 03 41                          .......A        
```

The reply from hsphfpd is: `hsphfpd.pl[1275]: Returning DBus error org.bluez.Error.Canceled: Device "/org/bluez/hci0/dev_00_66_19_30_9A_3C" does not support profile "hfp_hf"`

Unnecessary to say that is does work perfectly with my mobile. A VAVA MOOV28 lying around does work perfectly, also.

I don't know if the problem is in hsphfpd, but any assistance will be appreciated.

BTW: I have seen an inconsistency: in line 2269, uuid `0000111f-...` is registered with profile `hfp_hf`, where in 2419 the uuid is for hfp_ag and `111e` is for `hfp_hf`. Is this intentionally the case?

**Comment by pali** [comment]
> BTW: I have seen an inconsistency: in line 2269, uuid 0000111f-... is registered with profile hfp_hf, where in 2419 the uuid is for hfp_ag and 111e is for hfp_hf. Is this intentionally the case?

This is correct. `bluez_register_profile` here registers local profile 0000111f- (HFP AG) for remote profile hfp_hf. In HFP profile always one side must be AG and one HF. In all places hsphfpd.pl uses names of remote profiles.

> The reply from hsphfpd is: hsphfpd.pl[1275]: Returning DBus error org.bluez.Error.Canceled: Device "/org/bluez/hci0/dev_00_66_19_30_9A_3C" does not support profile "hfp_hf"

Could you please provide full output from hsphfpd.pl?

**Comment by svenihoney** [comment]
Sure, here it is:
[connection.log](https://github.com/pali/hsphfpd-prototype/files/5598998/connection.log)

Stopped PA and hsphfpd by `systemctl stop ...`, then started hsphfpd and pulseaudio.

**Comment by pali** [comment]
In do not see in that log any `Returning DBus error org.bluez.Error.Canceled: Device "/org/bluez/hci0/dev_00_66_19_30_9A_3C" does not support profile "hfp_hf"` error.

In log is error `Returning DBus error org.hsphfpd.Error.Failed: Connecting SCO socket to device "00:66:19:30:9A:3C" failed: Function not implemented` which is result of `connect` syscall on SCO socket. So it seems that either your bluetooth chip or remote device rejected to create SCO connection (for audio transport).

**Comment by svenihoney** [comment]
I had two different kinds of error, this one and the one reported before. I get the following when I remove and re-pair the buds:
```
Nov 25 21:32:59 willi hsphfpd.pl[123965]: Use of uninitialized value $adapter in hash element at /usr/bin/hsphfpd.pl line 2477.
Nov 25 21:32:59 willi hsphfpd.pl[123965]: removed: device=/org/bluez/hci0/dev_00_66_19_30_9A_3C
Nov 25 21:33:09 willi hsphfpd.pl[123965]: Registering application :1.1512 /SCOEndpoint
Nov 25 21:33:09 willi hsphfpd.pl[123965]: Registering application's :1.1512 /SCOEndpoint audio agent /SCOEndpoint/PCM_s16le_8kHz for codec PCM_s16le_8kHz
Nov 25 21:34:43 willi hsphfpd.pl[123965]: Returning DBus error org.bluez.Error.Canceled: Device "/org/bluez/hci0/dev_00_66_19_30_9A_3C" does not support profile "hfp_hf"
Nov 25 21:34:56 willi hsphfpd.pl[123965]: Returning DBus error org.bluez.Error.Canceled: Device "/org/bluez/hci0/dev_00_66_19_30_9A_3C" does not support profile "hfp_hf"
```

What can I do to further investigate my problem?

**Comment by pali** [comment]
This is strange error. Please run `qdbus --system org.hsphfpd` immediately when you see such error and send me an output. This will query via dbus devices which hsphfpd.pl see.

And please provide full output from hsphfpd.pl. Looks like it went into some undefined/strange state and without full log with that error it is hard to debug it.

**Comment by svenihoney** [comment]
The qdbus output is:
```
/
/org
/org/bluez
/org/bluez/profile
/org/bluez/profile/hfp_ag
/org/bluez/profile/hfp_hf
/org/bluez/profile/hsp_ag
/org/bluez/profile/hsp_hs
/org/hsphfpd
/org/hsphfpd/hci0
/org/hsphfpd/hci0/dev_A8_9C_ED_B8_15_CF
/org/hsphfpd/hci0/dev_A8_9C_ED_B8_15_CF/hfp_ag
/org/hsphfpd/hci0/dev_A8_9C_ED_B8_15_CF/hsp_ag
/org/hsphfpd/hci0/dev_E3_28_E9_21_EF_CB
/org/hsphfpd/hci0/dev_E3_28_E9_21_EF_CB/hfp_hf
/org/hsphfpd/hci0/dev_E3_28_E9_21_EF_CB/hsp_hs
/org/hsphfpd/power_supply
```
The Freebuds are not among the devices. The devices are my mobile (A8*) and the VAVA MOOV.

The full [logfile](https://github.com/pali/hsphfpd-prototype/files/5604382/hsp.txt) is attached.

**Comment by pali** [comment]
What is that problematic device? This one 00_66_19_30_9A_3C? hsphfpd.pl does not even see it.

**Comment by pali** [comment]
And what is the output of `qdbus --system org.bluez`?

**Comment by pali** [comment]
Now I fixes just small issue in git master branch which I found from your logs (Cannot send READ_LOCAL_EXT_FEATURES command to bluetooth socket: Network is down). But it is unrelated.

**Comment by svenihoney** [comment]
After reconnecting (not pairing) I have the following behavior: hsphfpd reports the following repeatedly about every 4 seconds:
```
Connecting audio transport for endpoint /org/hsphfpd/hci0/dev_00_66_19_30_9A_3C/hfp_hf with air_codec CVSD and agent_codec PCM_s16le_8kHz
Creating SCO socket
Returning DBus error org.hsphfpd.Error.Failed: Connecting SCO socket to device "00:66:19:30:9A:3C" failed: Function not implemented
Socket ready read: endpoint=/org/hsphfpd/hci0/dev_00_66_19_30_9A_3C/hfp_hf
Line: AT+VGS=7
Socket write: endpoint=/org/hsphfpd/hci0/dev_00_66_19_30_9A_3C/hfp_hf
Line: OK
```
The buds flash up in `pavuctl`, but disappear again immediately.

Seems like bluez is not able to create the connection:
```
Nov 26 19:52:57 willi bluetoothd[8596]: src/service.c:btd_service_connect() a2dp-sink profile connect failed for 00:66:19:30:9A:3C: Device or resource busy
```
If I stop hsphfpd and restart pulseaudio, the buds connect fine and I can choose A2DP with SBC just fine, and they play nicely.

If I then restart hsphfpd, I get a communication with the buds as seen in [hsp2.log](https://github.com/pali/hsphfpd-prototype/files/5604635/hsp2.log). Afterwards in pavuctl I see HFP as available, but if I select HFP it reports the "Function not implemented" and immediately switches to "off" in pavuctl.

> What is that problematic device? This one 00_66_19_30_9A_3C? hsphfpd.pl does not even see it.
Yes, that's the device.

**Comment by pali** [comment]
> hsphfpd reports the following repeatedly about every 4 seconds:

This is external request (from pulseaudio) to establish audio connection for HFP profile. Seems it always fails and pulseaudio is trying to repeat it.

> If I then restart hsphfpd, I get a communication with the buds as seen in hsp2.log. Afterwards in pavuctl I see HFP as available, but if I select HFP it reports the "Function not implemented" and immediately switches to "off" in pavuctl.

hsphfpd is required to be connected for HFP profile. So it is expected that pulseaudio fails in this case.


I have feeling from above description that your headset is not able to have established A2DP connection and audio part of HFP connection at the same time. This could answer why bluez see `a2dp-sink profile connect failed for 00:66:19:30:9A:3C: Device or resource busy` and also why hsphfpd see `Connecting SCO socket to device "00:66:19:30:9A:3C" failed: Function not implemented`.

To confirm it, it would be needed to look at bluetooth packet sniffer (e.g. btmon or wireshark) and check why connection fails. In raw bluetooth packet could be more detailed error message.

If this is truth then such setup would be hard to configure on Linux as bluez bluetoothd daemon automatically tries to connect all profiles for particular device.

You may try play with `qdbus --system org.bluez /org/bluez/hci0/dev_XX_XX_XX_XX_XX_XX org.bluez.Device1.DisconnectProfile 0000XXXX-0000-1000-8000-00805f9b34fb` command for disconnecting particular profile (HFP or A2DP) to allow other one to connect.

**Comment by svenihoney** [comment]
If I disconnect the audio profile with `qdbus --system org.bluez /org/bluez/hci0/dev_00_66_19_30_9A_3C org.bluez.Device1.DisconnectProfile 0000110d-0000-1000-8000-00805f9b34fb`, the buds immediately disappear and start the connection loop again.

I have attached a btmon [trace](https://github.com/pali/hsphfpd-prototype/files/5604737/freebuds-connect.snoop.gz), from connection with A2DP and the end of the communication when switching to HFP. Obviously the problem seems to be in packet #613, where it reads `Status: SCO Air Mode Rejected (0x1d)`...

**Comment by pali** [comment]
Ok relevant part from that log is here:
```
< HCI Command: Setup Synchronous.. (0x01|0x0028) plen 17  #607 [hci0] 12.517330
        Handle: 256
        Transmit bandwidth: 8000
        Receive bandwidth: 8000
        Max latency: 10
        Setting: 0x0060
          Input Coding: Linear
          Input Data Format: 2's complement
          Input Sample Size: 16-bit
          # of bits padding at MSB: 0
          Air Coding Format: CVSD
        Retransmission effort: Optimize for power consumption (0x01)
        Packet type: 0x0380
          3-EV3 may not be used
          2-EV5 may not be used
          3-EV5 may not be used
> HCI Event: Command Status (0x0f) plen 4                 #608 [hci0] 12.520265
      Setup Synchronous Connection (0x01|0x0028) ncmd 1
        Status: Success (0x00)
...
> HCI Event: Synchronous Connect Complete (0x2c) plen 17  #613 [hci0] 12.605265
        Status: SCO Air Mode Rejected (0x1d)
        Handle: 0
        Address: 00:66:19:30:9A:3C (OUI 00-66-19)
        Link type: eSCO (0x02)
        Transmission interval: 0x00
        Retransmission window: 0x01
        RX packet length: 0
        TX packet length: 0
        Air mode: CVSD (0x02)
```

And problem is that kernel does not try to Setup Synchronous Command with different Packet type and Retransmission effort parameters. You would have to report this issue to linux-bluetooth@vger.kernel.org mailing list and discuss how to fix it. I guess that 0x1d value (SCO Air Mode Rejected) needs to be added into switch table in `hci_sync_conn_complete_evt` function in file linux/net/bluetooth/hci_event.c to ensure that `hci_setup_sync` function is called again on failure.

**Comment by pali** [comment]
I have another idea. Your headset said `SCO Air Mode Rejected` for `Air mode: CVSD`. Also it said that it supports `mSBC` codec via `transparent` air mode. Maybe its default air mode is transparent and not CVSD? Could you try following patch and provide full log again? With this patch hsphfpd would think that there is no default codec when more are supported and therefore it would negotiate codec selection prior opening SCO connection.
```diff
diff --git a/hsphfpd.pl b/hsphfpd.pl
--- a/hsphfpd.pl
+++ b/hsphfpd.pl
@@ -1648,6 +1648,7 @@ sub hsphfpd_socket_ready_read {
 				my @hf_codecs = map { exists $hf_codecs_map{$_} ? $hf_codecs_map{$_} : "hf_codec_$_" } @hf_codec_ids;
 				print "HF codecs:\n" . (join "\n", @hf_codecs) . "\n";
 				$endpoints{$endpoint}->{hf_codecs} = \@hf_codecs;
+				$endpoints{$endpoint}->{selected_codec} = '' if @hf_codecs > 1;
 				hsphfpd_update_codecs($endpoint);
 				hsphfpd_socket_write($endpoint, 'OK') or return;
 			} elsif ($line eq 'AT+CIND=?') {
```

**Comment by svenihoney** [comment]
You know what? This works perfectly! I can switch to and from HFP, and the audio output and input works as well! You make Huawei a very happy company since they won't get a pair of headphones back! ;-) 
[Logs](https://github.com/pali/hsphfpd-prototype/files/5605168/freebuds-working.tar.gz) attached for reference.

P.S.: You should really think about renaming this project. Each time I had to type hsphfpd I had a typing error ;-)

**Comment by pali** [comment]
So is above patch enough for fixing it?

**Comment by pali** [comment]
In HFP specification is written:
> The AG shall initiate a Codec Connection only if the HF has indicated support for the Codec Negotiation feature and has sent at least one AT+BAC on the current service level connection. When selecting which codec to use for a codec connection, the AG shall use the information on codecs available in the HF as provided in the most recently received AT+BAC.
> 
> The AG shall inform the HF which codec ID will be used before establishing the Synchronous Connection. If a codec has been successfully selected at least once on the current service level connection, the AG does not need to inform the HF about which codec to use unless a change of codec is required for the next synchronous connection. If the HF has sent an additional AT+BAC after the completion of the Service Level Connection procedure, there may be a need to re-select the codec.


So I slightly modified above change to always force negotiation of codec after AT+BAC was received. Now it is in git, so closing this issue.
